<Project>

  <PropertyGroup>
    
    <EnableWindowsTargeting Condition="'$(EnableWindowsTargeting)' == '' and !$([MSBuild]::IsOSPlatform('Windows'))">true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>false</InvariantGlobalization>

    
    <Version>2.0.15</Version>
    <Product>Orbis Stream</Product>
    
    <Company>Marco Amleto Guarino</Company>
  </PropertyGroup>

</Project>
