<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Orbis.Stream.Core</RootNamespace>
    <AssemblyName>Orbis.Stream.Core</AssemblyName>
    <LangVersion>latest</LangVersion>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.1" />
    <PackageReference Include="System.Management" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Messages\*.properties" CopyToOutputDirectory="PreserveNewest" />
    
    <EmbeddedResource Include="Ui\*.json" LogicalName="Ui.%(Filename).json" WithCulture="false" />
    <Content Remove="Ui\*.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Orbis.Stream.Tests" />
  </ItemGroup>

</Project>
